### ISSUE TITLE
Benchmark with constants other than 2 for linear allocation.

### ISSUE THREAD

**Issue by polarker** [MarisaKirisame/MemoryBalancer#26]
// I read your paper on Zhihu, but I cannot reply to your post due to verification.

It's a nice paper with a beautiful result. However, I guess 2 is not the optimal constant for linear allocation on V8. It would be interesting to benchmark with other constants (e.g. 1.5).

**Comment by MarisaKirisame** [comment]
Thanks. This is a good question - in fact, our reviewer asked exactly this question.
In the end, we refrain from modifying the baseline in any significant way, as v8 does not have one set of parameter; instead, v8 have multiple knobs, which all can be tuned individually. Furthermore, the v8 GC is already carefully tuned by a team of experts. It is thus unclear whether we can change that constant while keeping performance reasonable.

**Comment by polarker** [comment]
I am also not too sure of the no-arbitrage condition. When a user opens a new tab, I guess they usually like the tab to allocate memory faster than the other inactive/background tabs.

**Comment by MarisaKirisame** [comment]
We did indeed talked about this in the paper! In particular, we can give a thread 'higher priority' by giving it a higher c priority.

**Comment by polarker** [comment]
Thanks for the reply!
